### PR TITLE
Fix for "apply all", which currently only applies one change at a time

### PR DESCRIPTION
**Pull request by ebmschmidt**
migrateAll() expected a return value from SchemaManagers's executeMigration() which no longer exists.

### CODE REVIEW

**Comment by dready** [comment]
Hi there,

catching the exception without telling the user why it happened is not a good idea. The reason we through exceptions instead of return codes was indeed that we where looking for errors and did not know what happened.

In our case we needed the error for our ci system so we knew why it did not work. Do you have another agenda? Maybe we find a solution which will work for both?

bests

**Comment by ebmschmidt** [comment]
As far as I see, executeMigration() already prints the error before throwing the exception.

The fix I wrote just restores the expected behaviour of "apply all" which is, well, to apply all migrations and not just one. As it is right now, it will never get a positive return value in Apply.php:91 and break the execution after the first migration.

**Comment by dready** [comment]
Then i would suggest removing the result check but not catching the exception. Before the change from bool return to exception we always stopped if something went wrong. 

If you have additional migrations that depend on the one broken it may have weird results in the database. Therefore we always stopped right where the trouble began.

**Comment by ebmschmidt** [comment]
That's fine for me, I removed the check. As long as it goes on if everything's ok - that led to weird results, too... ;)

**Comment by dready** [comment]
great, thanks! i merged it.

**Pull request merged**
